In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn import datasets ## imports datasets from scikit-learn
data = datasets.load_boston() ## loads oston dataset from datasets library

In [4]:
print(data.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
print(data.feature_names)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [18]:
data.info()

AttributeError: info

In [13]:
#define the data/predictors as the pre-set feature names
X = pd.DataFrame(data.data,columns=data.feature_names)

#Put the target (housing values -- MEDV ) in another DataFrame
y = data.target

In [14]:
X.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88

In [15]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

# Train &Test split

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test , y_train , y_test = train_test_split(X,y)

# DATA PREPROCESSING

In [18]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
#Fit only to the training data
scaler.fit(X)

StandardScaler()

In [19]:
# Now apply the transformations to the data :
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Training the Model

# 1.Linear Regression

In [20]:
from sklearn import linear_model

In [21]:
model = linear_model.LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [22]:
predictions = model.predict(X_test)

In [23]:
predictions[:5]

array([25.07349315, 37.9541279 , 16.77796422, 16.66921768, 12.4913969 ])

In [24]:
y_test[:5]

array([23.1, 48.3, 18.1, 19.3, 11.8])

In [25]:
model.score(X_test,y_test)

0.6982339940130406

# 2.Decision tree Regressor

In [26]:
from sklearn.tree import DecisionTreeRegressor

In [27]:
DTR_model = DecisionTreeRegressor()
DTR_model.fit(X_train,y_train)

DecisionTreeRegressor()

In [28]:
predictions= DTR_model.predict(X_test)

In [29]:
predictions[:5]

array([23.4, 46.7, 17.8, 14.4,  8.4])

In [30]:
y_test[:5]

array([23.1, 48.3, 18.1, 19.3, 11.8])

In [31]:
DTR_model.score(X_test,y_test)

0.6483303189476123